name: Go Test and Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests-on:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.x"
      - name: Go Environment
        run: go env
      - name: Verify Go Modules
        run: go mod verify
      - name: Build
        run: make build
      - name: Run tests with Race Detector
        run: |
          pwd
          ls
          make test
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run staticcheck
        run: |
          go_dirs=$(go list ./... | grep -v '/docs')
          staticcheck $go_dirs
