name: Go Test and Lint
on: [push]
jobs:
  tests-on:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.x"

    - name: Go Environment
      run: go env

    - name: Verify Go Modules
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run tests with Race Detector
      run: go test -race -vet=off ./...

    - name: Run Revive Linter
      uses: morphy2k/revive-action@v2
      with:
        config: revive.toml

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

