name: Tests
on: [push]
jobs:
  tests-on:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run tests
        run: go test --short ./...


